### ISSUE TITLE
0.1.0a1 release - Internal Beta

### ISSUE THREAD

**Issue by dvdjlaw** [data-describe/data-describe#220]
- [x] Update using new interface #126
- [x] Internal testing of core features
- [x] Ensure tutorial/example notebooks are running properly #192 #186
     (Test on different OS platforms:)  #179
    - [x] Windows
    - [x] Linux
    - [x] Mac
- [x] Create guide/documentation for beta testers and complete onboarding #97 #161 #163
    - How to install
    - How to file an issue (bug report)
    - Add testers to private repo
- [x] Host API documentation #97 #96 #31
