### ISSUE TITLE
0.1.0b1 release - Open Beta

### ISSUE THREAD

**Issue by haishiro** [data-describe/data-describe#221]
- [x] Bump version
- [x] Validate publish to PyPI / Test PyPI (#2)
- [x] Clean up GH Pages #31 #96
- [x] Validate/finalize pipeline for building auto generated API docs #97
- [x] Host and clean up API docs
- [x] Clean up Docker images #176
- [x] Coverage reports #61
- [x] Announcement Article / Blog
